# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

#Build all projects
steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  enabled: false

# Build the projects using Powershell
- powershell: |
   $project_files = Get-ChildItem -Path "$(Build.SourcesDirectory)" -Include "*.csproj" -Recurse
   $dotnet_path = "$env:ProgramFiles\dotnet\dotnet.exe"
   $project_files | ForEach-Object -Process { & $dotnet_path build $_.FullName '--configuration' $(buildConfiguration) }
  displayName: 'PowerShell Script to execute dotnet build'
  enabled: false

- task: PowerShell@1
  displayName: 'PowerShell Script'
  inputs:
    scriptName: psbuild.ps1
    arguments: '$(Build.SourcesDirectory), $(buildConfiguration)'
  enabled: false

- powershell: |
   psbuild.ps1 $(Build.SourcesDirectory) $(buildConfiguration)
  displayName: 'PowerShell Script to execute dotnet build'

#Publish all projects artifacts to Build.ArtifactStagingDirectory
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    projects: '**/*.csproj'
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
    publishWebProjects: false

#Publish all projects artifacts to Azure Pipelines
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: PublishedAartifacts